import { Code, Star, Trash2 } from 'lucide-react';
import { ISideBarItem } from './interfaces';

export const SUPPORTED_CODING_LANGUAGES = [
  { value: 'auto', label: 'Auto Detect' },
  { value: 'plaintext', label: 'Plain Text' },
  { value: 'abap', label: 'ABAP' },
  { value: 'apex', label: 'Apex' },
  { value: 'azcli', label: 'Azure CLI' },
  { value: 'bat', label: 'Batch File' },
  { value: 'bicep', label: 'Bicep' },
  { value: 'cameligo', label: 'CameLigo' },
  { value: 'clojure', label: 'Clojure' },
  { value: 'coffeescript', label: 'CoffeeScript' },
  { value: 'c', label: 'C' },
  { value: 'cpp', label: 'C++' },
  { value: 'csharp', label: 'C#' },
  { value: 'csp', label: 'Content Security Policy' },
  { value: 'css', label: 'CSS' },
  { value: 'cypher', label: 'Cypher' },
  { value: 'dart', label: 'Dart' },
  { value: 'dockerfile', label: 'Dockerfile' },
  { value: 'ecl', label: 'ECL' },
  { value: 'elixir', label: 'Elixir' },
  { value: 'flow9', label: 'Flow9' },
  { value: 'fsharp', label: 'F#' },
  { value: 'freemarker2', label: 'FreeMarker 2' },
  {
    value: 'freemarker2.tag-angle.interpolation-dollar',
    label: 'FreeMarker 2 (Angle Tag, Dollar Interpolation)',
  },
  {
    value: 'freemarker2.tag-bracket.interpolation-dollar',
    label: 'FreeMarker 2 (Bracket Tag, Dollar Interpolation)',
  },
  {
    value: 'freemarker2.tag-angle.interpolation-bracket',
    label: 'FreeMarker 2 (Angle Tag, Bracket Interpolation)',
  },
  {
    value: 'freemarker2.tag-bracket.interpolation-bracket',
    label: 'FreeMarker 2 (Bracket Tag, Bracket Interpolation)',
  },
  {
    value: 'freemarker2.tag-auto.interpolation-dollar',
    label: 'FreeMarker 2 (Auto Tag, Dollar Interpolation)',
  },
  {
    value: 'freemarker2.tag-auto.interpolation-bracket',
    label: 'FreeMarker 2 (Auto Tag, Bracket Interpolation)',
  },
  { value: 'go', label: 'Go' },
  { value: 'graphql', label: 'GraphQL' },
  { value: 'handlebars', label: 'Handlebars' },
  { value: 'hcl', label: 'HCL' },
  { value: 'html', label: 'HTML' },
  { value: 'ini', label: 'INI' },
  { value: 'java', label: 'Java' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'julia', label: 'Julia' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'less', label: 'LESS' },
  { value: 'lexon', label: 'Lexon' },
  { value: 'lua', label: 'Lua' },
  { value: 'liquid', label: 'Liquid' },
  { value: 'm3', label: 'M3' },
  { value: 'markdown', label: 'Markdown' },
  { value: 'mdx', label: 'MDX' },
  { value: 'mips', label: 'MIPS' },
  { value: 'msdax', label: 'MSDAX' },
  { value: 'mysql', label: 'MySQL' },
  { value: 'objective-c', label: 'Objective-C' },
  { value: 'pascal', label: 'Pascal' },
  { value: 'pascaligo', label: 'Pascaligo' },
  { value: 'perl', label: 'Perl' },
  { value: 'pgsql', label: 'PostgreSQL' },
  { value: 'php', label: 'PHP' },
  { value: 'pla', label: 'PLA' },
  { value: 'postiats', label: 'Postiats' },
  { value: 'powerquery', label: 'PowerQuery' },
  { value: 'powershell', label: 'PowerShell' },
  { value: 'proto', label: 'Protocol Buffers' },
  { value: 'pug', label: 'Pug' },
  { value: 'python', label: 'Python' },
  { value: 'qsharp', label: 'Q#' },
  { value: 'r', label: 'R' },
  { value: 'razor', label: 'Razor' },
  { value: 'redis', label: 'Redis' },
  { value: 'redshift', label: 'Redshift' },
  { value: 'restructuredtext', label: 'reStructuredText' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'rust', label: 'Rust' },
  { value: 'sb', label: 'SB' },
  { value: 'scala', label: 'Scala' },
  { value: 'scheme', label: 'Scheme' },
  { value: 'scss', label: 'SCSS' },
  { value: 'shell', label: 'Shell' },
  { value: 'sol', label: 'Solidity' },
  { value: 'aes', label: 'AES' },
  { value: 'sparql', label: 'SPARQL' },
  { value: 'sql', label: 'SQL' },
  { value: 'st', label: 'Structured Text' },
  { value: 'swift', label: 'Swift' },
  { value: 'systemverilog', label: 'SystemVerilog' },
  { value: 'verilog', label: 'Verilog' },
  { value: 'tcl', label: 'TCL' },
  { value: 'twig', label: 'Twig' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'vb', label: 'Visual Basic' },
  { value: 'wgsl', label: 'WGSL' },
  { value: 'xml', label: 'XML' },
  { value: 'yaml', label: 'YAML' },
  { value: 'json', label: 'JSON' },
];

export const sideBarItems: ISideBarItem[] = [
  {
    id: 'snippets',
    title: 'Snippets',
    icon: Code,
  },
  {
    id: 'favorites',
    title: 'Favorites',
    icon: Star,
  },
  {
    id: 'deleted',
    title: 'Trash',
    icon: Trash2,
  },
];
